apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgres-operator
    repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    releaseName: postgres-operator
    namespace: infra
    valuesFile: values.yaml
