ANTHROPIC_BASE_URL=http://192.168.68.122:8000 \
ANTHROPIC_API_KEY=dummy \
ANTHROPIC_AUTH_TOKEN=dummy \
ANTHROPIC_DEFAULT_OPUS_MODEL=Qwen/Qwen3-Coder-Next-FP8 \
ANTHROPIC_DEFAULT_SONNET_MODEL=Qwen/Qwen3-Coder-Next-FP8 \
ANTHROPIC_DEFAULT_HAIKU_MODEL=Qwen/Qwen3-Coder-Next-FP8 \
claude
