apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: promptyard
  namespace: argocd
spec:
  description: Promptyard prompt management application
  sourceRepos:
    - https://github.com/infosupport/promptyard
  destinations:
    - server: https://kubernetes.default.svc
      namespace: promptyard-staging
    - server: https://kubernetes.default.svc
      namespace: promptyard-prod
    - server: https://kubernetes.default.svc
      namespace: promptyard-dev
  clusterResourceWhitelist: []
