---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: promptyard-staging
spec:
  encryptedData:
    .dockerconfigjson: AgA3ieF/ZN0/y6aH9zZAKbleTT/uTGLHnuNoaOoxHDgevy6+YGD7yFgjQh0MANZwhf3p5tTj7b8ZGSDpnVX0eHDXKo1fug9j6YN6KDffvD7sTwI8KIVJ5F4PbZNHndZiB7LCGYZrYgLQzAUHyKmul7EyrPOzdBmaBAHL8YyS5kGGn01ZtgC7mMSElWmDLhYhVA5xtN+93oXk4nnjgraMYBhY9x5isYOv1JRAQSq3ylvIu9YgAV5MwUVBDMZJ3eDGifdr1aHUn0xyiRv90hXAEMYOSAXgJLAWcESui6zufGvHPlxtrVKIG19yAiQH9F7hEYz51Y8EpHzmfosI4Ox7kIpA+8lkKs80To8E3qgT344+tsn25W1FP3VXPUaK0dOQ+KXQ1odkdAFTLrKXyNAJpOcIxggDpwveSR73N3hPAEG9usqjBsT1APMB+6tyn3RnKS0Bu3kmLwiFkxWVHL8yH4XHZh4kVrlJKIwhdrXnWjPnmprkILK7AEaBla+sRvbFHKKWYElGGmVHaUZ2jsyD+JZepqf4CifXixLPwihJ0omiVLc+ZRsWS1Cn+ZnodEge1bcCoj2hwhLX8EX52OqqopMWnSD9RC8XJvbeelTyAIG0e3+FYpqcxabze/MlawgVhlEa96x3UWaEW5MhOT0Oly2gTOsIk1fIz4F6zLP0+eBbi8E2H/wJ1SF4PQTzfFGySYqH/VW3cQTLZyDLYAr/dtdSbjxSQhZ05QErlwtVKJwfJhgzoE4v/zbu5OLpP3m5p7tvG+oaBxpJGBLZX1eHdv5Zezzc38e0h7Yh+fwNwkFFGELADaM+qaLJYNS+rA9ajQCsS4eUQK+qY07kHmuSzLBMXWmo7W5/03M4D2/h6ATySPILPzFKQ0a98jKmerJUA8IJMqw3uMCxAd6cg9sF2euabm2+uINKTeUdenp4dl72aW+ToY05x2UOgSwVUxgbJKdJ1uVV/BEJ3XelK4cDcuB3P1NvJVCbfcTeVmmN
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: promptyard-staging
    type: kubernetes.io/dockerconfigjson
