apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: promptyard-staging
spec:
  encryptedData:
    KEYCLOAK_ADMIN: AgAcsqjvYUpGJtawa4f36y4W/wx1fu+8vgnrPvPaI1Xn5PAuNcawFiS6C8U24vn8MtYz059nMJp3osVj13X8AqgusYB6FeAzCgwXfKNkloSZiWyWdQGTHrkPzo/0eUB0/cvPCwmAZgf6KFv60qFZwlg384ouGruHvmRyGme9AXRDCWqgg/jjg0q+F49TxkwPLXl94HxZ9CyUUlRUM6N9kBNo/jU7+sJiWMiFikFU3K1BzecnSFlOy8EG6Sl5fxoqjzO6Wopbn6Ex9P3QtFt41eLX5eaGaNYGo8iophHwKVvqhhchl44IOsMjyk59liBmMEaOTYxSZd40XbbbJXXcG53h3UAWpA3J1t20JPdMKdDQyO5jiM/pWNSCQxK7PxQLyGxERmZfWS9B93QkM5JRFKY4HCrOG+yCtJMDm/N1ilmVH5kAO3YUm93tneuruNhVpQcHRWYxmVscKXdmn2nH+aQ4hqHfwVr67BqQBEWOfnqd3OtOVMSybKdq7vC99gguvOkCu1dmvbrqUMk+It7A5ZEZa55JTfmuovh6AZ8os1Hh7CJLk5RsTIxwolPPYqn/6wOCz7EBlk7t+7lruwpw4AznRqmTKzdIQC3DXaTEd8btWZjVbYMrWcDTiLawHwejuVAO8qxtoc/D5IEeqg8SARzSSmSFZO2sIdJ/I/F7jjXUCPWQupl4Qag4JiSZyfVVXNUgSFaqZQ==
    KEYCLOAK_ADMIN_PASSWORD: AgCHw6Vwm/X2lLPck+mEEWiFkxBAGZDLn3J07eO1JHyxWyK6E9jg8W4BVdoQvZMP2QsQWiAQkMPstCsTfL6nSW0SbzDpBBeQDXi5X6/vpOcojFr8Tt9FMmbqVZSnBuaSS8HEatrpvfD5c5x8ZqeALZ/AYYM4gZxMO8H21FY/O/cLvRuUm1hWHFlhVJhvfURxhbAUezNX2/i3QUiQVwL6hHc0LYIvk4XmURSo12PrwR8oYDJSKdXuqCKSiOLIiUzJJ1mZbViLPF3Nio+glZNIP0mL6RJjX8AjhGlB5NMjYfzwA7jz9psrH4+ZseovJaLvCJo/LCQcBq9w4ExDn5C/zYVlmsf3o/eDK/PmZm85iQn1aqxnPgUNNBzUC9yvLGc1/esEm+uXjXvDGc87XNNXTfeKeuQO32JEMwlVhengz4Dm7XcHI9pkzB0Cm/6WTZIbjyyRMWX+LR0mvtZhcg5857eKGsEiJLE52sdBAxBczrk1vKGEWDWAAiySVqDC9SqQJVwT/dG+ydi1LQVvLy2c7hEAFPPr4odXGl1eT6CCb29yXfGeQr2MIwRj9n0018NcYiwKA/8SpWxT74i1+ZMzl+5vbBbMo7jdMeaM4qNQ7vjBt33Ux0h+J8WFi0UFkc4LoFsHcJYqnRr9GjurUHJl4ciWyDD98vxhu4LRpQdpmzwoRgMsZBbX8QBsKWK0RhBy1EMi2m/r/CU2fJYVoJU5zsgjv5Q1vDZNIJhp9VIi7O8p7w==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: promptyard-staging
    type: Opaque
