apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: promptyard-staging
spec:
  encryptedData:
    KEYCLOAK_ADMIN_PASSWORD: AgC4JXZBmHEhVRdAHcTfP3vNOK4eXRDSvGGbtcDEoAkgUMdIJ8KYfjYsGVKh2CI1ZqY7E9zz9nKPzsPMU9xjzmZD2iAlLENwFiEcBXb8msJ4CSpVgd5IMVw+Ni5yoUafvuz3fsXoI5NEi/PBgmvpB0ArJv9ud8QM59y2hAagATJNA0vteuMxrPfOufa6JxDbY6Q2mJvfSoPwW2KjUAJu5/moWliy1dzEKmuEPIKoyJiEwfzfCZqjguyVExmqtIRyJ/wQJfdcvRuzCqT/5E0iFNUBTG+iY2fXraadsm1vuHK6TlPQVaumLYtrBa3hswse+edEcAaiJhcYCgzcgcQFXfQDW7VFoaNulCavEsthN6sSk6OmyHpNwD2vgAvpYgb1yRx4sTGYzWSrpgddZs1jjfMw/Fhgh3Zy7HYV3OlV1bCTHomeqSIdLVmhXg4aByld3PtyJqZstIBcvqWUzYEAoURvvVnuVt7KpVrmFWaKuiKka1MF6Y/Flyigm9qAk16VGWUSPDToVl0k3U9f8osuvP1zSkkIvWkvUG9A3vFZFFkKihvUU77u89vRROnF/6iR9G5/2DfMfi2wbXAu7z25HFJmpbLGW20SFvx/AFrD/cdNUiiRcEOsnSM2p9N0bLDqv8aeJH2aXOi1Gd/RoJ2B//EALF/pxXMBQuOFxFjEgjo6t+HEoJraLv8zV3ei9FL0FwbUoxd28Zqe++6Pyx3ddbyC79hBP12R0IlRI+kLgqgvVg==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: promptyard-staging
    type: Opaque
