apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: promptyard-staging

resources:
  - ../base
  - namespace.yaml
  - configmap.yaml
  - promptyard-server-secret.yaml

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/ingress-patch.yaml

images:
  - name: acrpromptyard.azurecr.io/infosupport/promptyard
    newTag: 6dee084bbdb83f23df79e882ec3a43d3ba933fad
