apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: promptyard-staging

resources:
  - ../base
  - namespace.yaml
  - configmap.yaml
  - promptyard-server-secret.yaml

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/ingress-patch.yaml

images:
  - name: acrpromptyard.azurecr.io/infosupport/promptyard
    newTag: d97282b03f272546686f9b941dcd56bd94512380
