---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: promptyard-opensearch-admin-credentials
  namespace: promptyard-staging
spec:
  encryptedData:
    password: AgCqxYnmopVbinW0DrUIIUPbToataxRE7k46J5FlXGbpadUU/V5HBuL+WxAAVdtEeexC+Q8j0GV9lMRwHWolLiQFNOi61N7pyav5V/5HprrbqpjNQXUjprjNlcubaDPvMOt4yjjml0+a0/psrZhiPm2hmleJOfJalz8nCKulo4f7Lmj1JulKZ3JcDmiZVsWlpVMi0CcGhln/UOPjLb0FayZOL9vua3RCfTQRFywKOCFedLZDT6HwmBZHom3LhE2COarIaowN+waNP31CNkZQpC8BecgfAaRpl4HVB+IRj+AmnRY2G0OqTs0C3T410Dxfv6QmRpS0tV+7G+FvdOgdSt/MlTNS8wp2Z4gR/leAPMWMUL43tH/KLewcU9Pyt5F+EfPW9IRmbpwkqHmJdMeecNvAcGMxZbMtaT8nsCI2prwoODYx/eXPCepf4mnCzGf600nRCZ7MbV9UTWJz5lafIZ7a2/77vFLH0/smUdCTe1t2R67k69VqdMm6TGhQOPcpB5LKN3idsgeRHU9qH21KSeDRtrJmGXcJyYSW+PsTl7H27FVL7PLvv40zoKEcfz8HqrJtQUvtyclsJx5424zpaILp8gvZR4SSnJ3McQRcpY4rST4dZlSZGW4F4OBx761LMCNLFHOyLgZdhd4twg66pPNlwyPmGZLiClV5kgjG/9UNXpuhGOSBDfHfmWEIZFVLrAtUQa/xG10bqwhJieV2P8kfyQmmvtC/Y78UwiNKCtsWtA==
    username: AgC2tTYI3xNs1S+x/PD04eBpLl84OdqjR/bZB1aVCPync+qwsx2XH/Ia1yBPOj8X6U72m0b7g843yHz35Zc9vvhgFdR2N7Xy64whur6h3IOCpNiqc8V/wrtaHjufCbjquE3y7dBWR7AaTlTYFc/c0CC03/tN3W5sOIPRRBIvQDdCtOHuEG1n2AIaachNDHQ4cx6p6YhMhPT/Pam+8O0sN8GkdTlsCYyW7ZyI0asGQxE8q3v6S0fkpygCm91V/I7SeTWC9O/e0gYRAGWeVKa/aKwf/ij/nV5OGfRfSj/Z4SYjBhTUcBbcCJ510UZ1e2pPY7DZvxFinZpvKlqtFB5OlHnV5Q+b8/XAdeaAYvWijVP/OlZZKu2YlNR/XlPflFZTZ41LH4sF+DRKYEEc+guOE1cjrlIRbTWyrchrZW+iuf/Y32mvjkpy6kE70pyBHe8bLD5zv/jEMWioOH1KPwDoOzaR73aWNCiTodEQocZ4x7tulmJoUTbPrdeurtcb2Y5XRCrA3HKKDPEeu2qo2rhmQzPrJsS0+VISHbJIGjK70a3QTki2pqv/N/465nIWSkevPLSVWnsgWbQ8XVSL73b1PEG2nS9P4H0BZe24arODcyz1inyQQjcVb3eWIv5z429BzO/1y4tnPLIXe8/nZbiQPmCdNZodEqyg5D44fn6zDquPLysp8SyxUnASYhGSumu0EUNVt2Odig==
  template:
    metadata:
      name: promptyard-opensearch-admin-credentials
      namespace: promptyard-staging
    type: Opaque
