---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: promptyard-server-secret
  namespace: promptyard-staging
spec:
  encryptedData:
    QUARKUS_HTTP_AUTH_SESSION_ENCRYPTION_KEY: AgCkMBsNokXBV2qCgkG1gkIIHLV7FdXHlWeTcb29tceSeljOwwMt5FFu4ualrKL69fRD+iGiaxAju4G0bKJxPiUaAsRfq34YGQwlp/KWpyK7WtmCFFGJp+9rdbG0zYJLcEUWTd2mh89zgXvxGrIuOruUakOxolT6dtsrcv1uKuoY3Ic/WfAF4BdH5JsjTKqxLGIvEXJaL5NDkNrFBAVgkPfDWSNZ9OPBbzTEVeDkPA8MiKGWocC/ErPP6ivN/z9qRIdnbw/X2ZlJJB1jt5maBktKftOEYYWH6Sn40fr0lEoM/b/u4CkKuPSHYHvnf0hSA9+DtFnvlPXfJ6v7Fx8J4p/9IqytCMEyCfwltpmdKUTxAz8d2oJMvaVtnycB/T3TsUPpW95+nXMv0KdHkQjPDIaxloEsg388vA6KRejCpHJpxLjBX2m4OEG6BWn/2UlKzR6BbshwrJDdqTE80BOkQ4yep+TFGZwkYfYXEv2muZ71uIGsB03HINp04Nh7OLMRM4pY9wi9HGxsG7rDNQ+GyVos3uyVk8QrJz31WaQVHcgU8H2y00ZSQBActyAKgMDW0Uv7BOLGkQmzU5OlKoq6DF1boSgKqm+ryZfdag2gQEUsvz+Q0ghyPhasCIspG+MRJfOJ1Rlg2MpPE/6Cmb6o25J/TwAkpagx+eLLoj2y485yp2h1k9PGZqtWPwsQr5JVCOoDl51aBlhCp33w7qieqcLczBnEuLQ64wab+jkziUvKSllOOAJef2SwsQFV0o/3dY30n4AC8TNVN07gMBeWyEmI
    QUARKUS_OIDC_CLIENT_SECRET: AgBTC+qxFdicut1h78rx3HquE9dLScQW08voW939SvZ87jyMwrnk4YHgESVbsFpp7uXUCwTVj8YYMyrm8t0uM7lJO7Yx1u2fVMFHgiv00FiKT5JUIFjA9enJeQpTaZuwvKDz0T4TdG6W8cwrc6mATjLSYmFvt//1VUUI+gs1bYzufxP8Dr+SRjnz8JehR6FkCbjMJfX65NHFl/v2xIZHJBFBwbx5jumEe8N9HdTCZ/xEo/u0k/RxwTBjRuWzf9cxIH+YWZ07rOs0k+GPDOW9cO4bsF7nO20C+QZJ/C3ptRjhLsunfwkVjNeT0cmuB4mUnzVDkwxMZdag7LoSXbC35OpsMY2QvNmqO+pQgS1yl40zW9WRgy7A2gi5dRyZivy6/5A2SibPETRqEF+TDsFMbKu8LtaB4TFe1ag02NRf27BA35DsBNXFSlnCa1YnSfISve7h3z+oipPECZUd63+EOiDrTiRLkmlz/tz4+eYPK3+kGuWn1/eFY8Jq0n+L2dDF17FFJlM6NodiOO7A4Nz/feuHvqZrTo3gB09ZQ/SRjwHyCKWAss82Ifo1mPNPVoyLwjoYXGrEURNwIwaSyT9Ex3DlpMJ0uMrvtNhtMEzk48KcNnoqbSGuZ5GiPxhCaodQ3X7eTfdRNYW4c3rY3PrTlz+p08Xl6w1Xw7EMnmJMEkQrkaLXKGQTxWL8kY4tA8ZyOLRGnsXyTLZIDQul7PXBa1+cpFg8Xo6v0j3qczi7ZlPxy0nda10yyRrD
  template:
    metadata:
      name: promptyard-server-secret
      namespace: promptyard-staging
    type: Opaque
