---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: promptyard-server-secret
  namespace: promptyard-staging
spec:
  encryptedData:
    QUARKUS_HTTP_AUTH_SESSION_ENCRYPTION_KEY: AgCkMBsNokXBV2qCgkG1gkIIHLV7FdXHlWeTcb29tceSeljOwwMt5FFu4ualrKL69fRD+iGiaxAju4G0bKJxPiUaAsRfq34YGQwlp/KWpyK7WtmCFFGJp+9rdbG0zYJLcEUWTd2mh89zgXvxGrIuOruUakOxolT6dtsrcv1uKuoY3Ic/WfAF4BdH5JsjTKqxLGIvEXJaL5NDkNrFBAVgkPfDWSNZ9OPBbzTEVeDkPA8MiKGWocC/ErPP6ivN/z9qRIdnbw/X2ZlJJB1jt5maBktKftOEYYWH6Sn40fr0lEoM/b/u4CkKuPSHYHvnf0hSA9+DtFnvlPXfJ6v7Fx8J4p/9IqytCMEyCfwltpmdKUTxAz8d2oJMvaVtnycB/T3TsUPpW95+nXMv0KdHkQjPDIaxloEsg388vA6KRejCpHJpxLjBX2m4OEG6BWn/2UlKzR6BbshwrJDdqTE80BOkQ4yep+TFGZwkYfYXEv2muZ71uIGsB03HINp04Nh7OLMRM4pY9wi9HGxsG7rDNQ+GyVos3uyVk8QrJz31WaQVHcgU8H2y00ZSQBActyAKgMDW0Uv7BOLGkQmzU5OlKoq6DF1boSgKqm+ryZfdag2gQEUsvz+Q0ghyPhasCIspG+MRJfOJ1Rlg2MpPE/6Cmb6o25J/TwAkpagx+eLLoj2y485yp2h1k9PGZqtWPwsQr5JVCOoDl51aBlhCp33w7qieqcLczBnEuLQ64wab+jkziUvKSllOOAJef2SwsQFV0o/3dY30n4AC8TNVN07gMBeWyEmI
    QUARKUS_OIDC_CLIENT_SECRET: AgCUJsyf5PEmwrx0ZykttKYJKbVdODIF8QBY3+285BjVFvQmmodCdFKp34NTIBsNSossKZwjT4BQI0saJ8pzYD1xf/gwucs1Y3gtcVlj2PqfGfVxQr46ND0v0facviCUR6vY2TSjOaLgeTaaVw4PzaEod3InPiXL+eoj8pZCbRrBziIFab9uRvcORZu1ILUmAas+lorcxFBw2puKW23NkJbJmztyuFx4d4hKXLqthhjrf2z2fA9uuepjFoexK0IJzwVowoOSswjoPFnenKBMhF6/w0uEV3JpiJi6RrgYy0jQZrBu/D2M0j3YmeoxDgi4bCUMCVsc9cq9gEAnVSd2YLxu6sPG6z6XkZG8a2OXx13ixevaJLXnSUIXZTyoeABsq20fgZ9z6walA33Q6Hj9KZnZuTsUJ2pkkxeZrpO++yFAkakcurFHXNDKNMJWUYEbKY98CBwdU5m2Qk8ld9RmM6n5TSTwMMs0htrAnR4TL/0KpkM4Qlnf2NqxqRQ1TiSmYPq8U5IBa8eGY0r6DiYJ9HYIjlNo4UDoV5d7teJ722o+0v8053L7JC0yGCP/t79s86QLSr5DwmVH4ycGMQCw7/SuEE/9JqHWhqy/ohkq9Q0089FLEE0IFXVShIxV+nRuWLVQdMoWmMCpXHkmzpQYEDyu03OPOIEFJRYUsZO8zlToJG8EkKAYC7xiNSjpXqMA9NeUHqfs6ZwsuO0FYRH0yA==
  template:
    metadata:
      name: promptyard-server-secret
      namespace: promptyard-staging
    type: Opaque
