apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: promptyard-opensearch
spec:
  general:
    serviceName: promptyard-opensearch
    version: "3.5.0"
    httpPort: 9200
    vendor: opensearch
  security:
    config:
      adminCredentialsSecret:
        name: promptyard-opensearch-admin-credentials
  tls:
    http:
      generate: true
    transport:
      generate: true
      perNode: true
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "5Gi"
      roles:
        - "cluster_manager"
        - "data"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
