apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/server
  - sealed-secret.yaml
namespace: promptyard-staging
images:
  - name: ghcr.io/infosupport/promptyard
    newTag: latest
configMapGenerator:
  - name: promptyard-server-config
    literals:
      - QUARKUS_OIDC_AUTH_SERVER_URL=<your-oidc-auth-server-url>
      - QUARKUS_OIDC_CLIENT_ID=<your-oidc-client-id>
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://promptyard-db:5432/promptyard
      - QUARKUS_OPENSEARCH_HOSTS=<your-opensearch-hosts>
generatorOptions:
  disableNameSuffixHash: true
