---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: promptyard-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBWQaK55ACAcxYyb0NVRO4H5f7nccBlI4uDOpyLCstMR7EnM0wGq4ipfkzJbbGqSidPT8FUwnf8qAMiZgTu7ZVs/UO5aw7EmPqp2BuZiJ1H6dq7cPUbAOmU+v9T4slIYYWSG+N5kMlwBQt1wfkl1UpDs5GlWJaWLnhIVaYh/ZiY/iwafhwJPk0fN8zoiPzIMzqc+vIpPDHhJKpAskF+GHHqjnGi2kKlVdUDgjIRfLmNj67//rPHdhQHnE2r767Te6g/SQg0pWvkzMQDc4OL83hsj1hlUjpejWLnd3nOZ8nFLM0P6EemhtUQbMcLX+H4FwmM1une6rSuci42o7bQkoVzuhBINifDeqntnhuU82q0faY6qopsAbgzu9K3RDYWc3zKKp2+qmMSzVIQRfUemmm+BNG9OUdGkaLysNsTuLEInXBSVcC/SChFwc05i3tpPV5mI62F2ToYZfTi5Volka3VCVV1qxL96gdkuR3wZf/4H9mCfdQVLiBd5UfxnnmUN1xt4BQuQG9kiIoivtRGC3LS0FOomhREcGAZvotLQ/ca14ZKF+JfZ0w6sZYfHhZCayBt5KqNfkglIW/3sbxb/bFMfBBti3K1j2zKiIzT2Q4a0GWxFC/C4QRTEj0Y0iusmnc+BbLQYaU7yUkuE6OP1TToDVuTR5xGsRFXG9mGKK5jRl9e58JyO7C/CjxOC7F4OA+z2Bj8GWCvPGL7tfZ3CUxSaYneFcb+feWtX/ehDs32QPWHup6bbJPWuDMZ1rmbDaw5dYPzQrdsYFSI+elX1ppqAylZTS6BVt39AKPPzXS8M5FcyhHAjOhpJubVVBORg4LBfSJzsJfbpMaZS5BYmFX2m6AqOgbuAUAT+Ws7gSIgT+/r+NLXU0PgP1AY11DV1uxTx4Iw/32y5Af7IIeF5iL9PzPbWZ6LktiRTIDjEZdRPgnAo3zqXCpnYZyaiWB8QPfXhk0DgBHWoAOY8YCrIsz3HU/i/p6dmgkbKh+p
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: promptyard-prod
    type: kubernetes.io/dockerconfigjson
