---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: promptyard-server-secret
  namespace: promptyard-prod
spec:
  encryptedData:
    QUARKUS_HTTP_AUTH_SESSION_ENCRYPTION_KEY: AgCZyihvrCSWZo8DFctS7srnbwzEdrd6+vFsO89VeOqa7oTy62WCc/ILLr2KT/rnSuOdi5Y9Bqsji7kN2MEl6Yf3JbpEBZBUeK64zA3hymEUFZXlFo9T3CjLJTZRgOXuuiuTr5ai8j8USS6531BG8a8L+hLTeRbk2MhDFqcRR4RDYl5+FHijk13ZnPnsf9qTWpWYvpVmFcIRmB3uE+2ifCHP6g+qqeLL9d+81YyrjWb/oSIbSCZkZrGzjk0aLOArglL03ZJqVHBuWTW6EgaTxlcSXktAcsSmDqG8Rn84m5yKLbaf/AGgGhtq50ZWcSm/oDLPupvWHthND3WSsGJ/H3kJAy85MZnSyMpUASBHq3o251Zd39695nNtH9aNtCsKCGTH1WDz6YjxwHSBoxDvXC0lf+JrTwbUrXvUR4qDUUmt+1f1V4KgQS/D0tLlS47tyvg+3y+R9nZ5XjqaJZHSSE2EquSCbARygggxiEWzwT173H23LN/cRAVHteMTLz0vJQj/cWnSkOIpJkwxSyHyYoNtAJ145KQ87OMJRmmRM26jGzw5LZwpM0raYHQd1K9KUmLdk23GXEx1JHb6OGnSRNLwCna1QlqFxs0BuvUgUIyM75O+gMMz646Hwi7TauAINozmd5SzeiyYZ5TCAjVIb5ZlU/TWFvbLBYhj2nGY4SOhiRde0uhoNQiiwjw4FFD5J74DPeP3ILBNayJOqdA6UvCgQxJEe/DDJTV71FIINCaIhUdEOSx86s+GnxQheQAezhQJGzsCO2PWWeAdsDyVAlzp
    QUARKUS_OIDC_CLIENT_SECRET: AgAE4xOwQTOyVvdjykKN72WZscW5vzBVpsg2OLkxVLgQnc4qyhyPA54x9tQoruebTlvFO711AY0tbYE6J/Rhaps+yMTo+y3mfiWIVnHH+SmUamh4anzPAiOgd9+wfM91uU34cLOvMzMAm3vahokxnzxe9y4ChH+I9fkhmXh4/PHy9DTvcCsyGLrXVGVP93uWqY3/Wlc6U2W5dL43LNqBO+PPqZeUB7Qju/X/HC8O//XheXt/aqrqMFBe9QPjrFrLpnwkQxxNSe/gkqsJo/P+NJCHIK9ALUdHqzbbWyuSnvveC1zcZDqv5rw4ORhNknYOZ3tM2ohbyuxsCb5uNWyWYkVN5j0YrhOV2yWQAlS8oG9fWG1slvZGrB1RIpPadzEFHmj/wWp1eAKlthhU01eQFr6FnYKBbCqcrxT/tjIc1SI+gD5rOkzP4+Uf8alb8lXTEUvpOt5mtjtGmPAkeFXQxYPZnHxojAHRnAowv66nrQ7wVp5yLTJ1i48sKsxNKqAV7gv7J+PPdsxFQSzis2xBDi4SJYgvqKk+jlV5+UASzJ45+SAGpvP/BSK3GgCO+rw7Z433S0O6TK5iL2/LXkYXDnSQc1nGZX80bO+fu39G9ZrjSwAGkiO6bLwDvQkeUUo++5KRgbDW4RqgHdr0E0xpDFN8MRFyQk2U7YouTXHWHrFQPcXz2YQwjrxOWIxDvLvBG7/FTgBztemeFkw56fO8Cg==
  template:
    metadata:
      name: promptyard-server-secret
      namespace: promptyard-prod
    type: Opaque
