apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: promptyard-server-secret
  namespace: promptyard-prod
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    QUARKUS_OIDC_CLIENT_SECRET: ""
    QUARKUS_HTTP_AUTH_SESSION_ENCRYPTION_KEY: ""
  template:
    metadata:
      name: promptyard-server-secret
      namespace: promptyard-prod
    type: Opaque
