quarkus.http.port=8080
quarkus.quinoa.dev-server.port=5173
quarkus.quinoa.build-dir=dist
quarkus.quinoa.enable-spa-routing=true
%dev.quarkus.quinoa.dev-server.index-page=/

# Authorization - require authentication for all requests by default
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# OIDC
quarkus.oidc.application-type=web-app
%dev.quarkus.keycloak.devservices.java-opts=-XX:MaxRAMPercentage=70 -XX:MinRAMPercentage=70 -XX:InitialRAMPercentage=50 -XX:MaxRAM=1G
%test.quarkus.keycloak.devservices.enabled=false
%test.quarkus.oidc.tenant-enabled=false
quarkus.oidc.logout.path=/api/logout
quarkus.oidc.logout.post-logout-uri-param=post_logout_redirect_uri
quarkus.oidc.logout.post-logout-path=/

# Datasource
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${POSTGRES_USER}
%prod.quarkus.datasource.password=${POSTGRES_PASSWORD}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/promptyard

# Flyway - run migrations automatically on startup
quarkus.flyway.migrate-at-start=true

# OpenSearch
%dev.quarkus.opensearch.devservices.enabled=true
%test.quarkus.opensearch.devservices.enabled=true
%dev.quarkus.opensearch.devservices.java-opts=-Xms256m -Xmx512m
%test.quarkus.opensearch.devservices.java-opts=-Xms256m -Xmx512m
%prod.quarkus.opensearch.hosts=${OPENSEARCH_HOSTS:localhost:9200}
%prod.quarkus.opensearch.protocol=https
