apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
spec:
  teamId: "promptyard"
  volume:
    size: 4Gi
  numberOfInstances: 1
  users:
    postgres: # database owner
      - superuser
      - createdb
    promptyard:
      - createdb
  databases:
    promptyard: promptyard
  preparedDatabases:
    bar: {}
  postgresql:
    version: "18"
