CREATE TABLE user_profile
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subject_name  VARCHAR(500)                            NOT NULL,
    slug          VARCHAR(500)                            NOT NULL,
    full_name     VARCHAR(500)                            NOT NULL,
    email_address VARCHAR(500)                            NOT NULL,
    business_unit VARCHAR(500),
    job_title     VARCHAR(500),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_userprofile PRIMARY KEY (id)
);