CREATE TABLE content_item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content_type VARCHAR(31)                             NOT NULL,
    title        VARCHAR(1000)                           NOT NULL,
    slug         VARCHAR(1000)                           NOT NULL,
    description  TEXT                                    NOT NULL,
    author_id    BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_at  TIMESTAMP WITHOUT TIME ZONE,
    content      TEXT,
    CONSTRAINT pk_content_item PRIMARY KEY (id)
);

CREATE TABLE content_item_tags
(
    content_item_id BIGINT       NOT NULL,
    tag             VARCHAR(100) NOT NULL
);

ALTER TABLE content_item
    ADD CONSTRAINT FK_CONTENT_ITEM_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES user_profile (id);

ALTER TABLE content_item_tags
    ADD CONSTRAINT fk_content_item_tags_on_content_item
        FOREIGN KEY (content_item_id) REFERENCES content_item (id) ON DELETE CASCADE;
