CREATE TABLE comment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text            TEXT                                    NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE                NOT NULL,
    author_id       BIGINT                                  NOT NULL,
    content_item_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT fk_comment_on_author FOREIGN KEY (author_id) REFERENCES user_profile (id);

ALTER TABLE comment
    ADD CONSTRAINT fk_comment_on_content_item FOREIGN KEY (content_item_id) REFERENCES content_item (id) ON DELETE CASCADE;
