apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ghcr-pull-secret
  namespace: promptyard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBoXXhSs6Mtm8M276BCcgTT34RwRlg6KtDB27JHv7qFEhzAot9rz5cjQ9R2Bd0BYxzg2Zq9+vFxap73ZYyMePebsvoY9xyfK9m22jpQN+njeQ7T7cd0S232PmVsjss7vU0tfXRkfhY7hOaiL8/290IfVPQQKoqf3kOem8BBEOxj2LHhpjLYWOuUwsROm0Rw+8qZRAYbUC5IXH4ptYP+DomNYgo98i+oiQvR6PP3nLLbGPGUL3F2UPOtRVe6CnXoWPQCKjMO2D5FWaxRxXj8kqZZ+UMKJD/zh7JgSKIUg/USwqC06JbJhuZUM+WAsilDiKDOSHYTMy0X/MSCRP7wiuqoalMtcNwoQpDryOFwOv0qScHb6n5nKbngaBfqmA+xndYvoAUH6JtgHKdiyO2++tCJUKahdQmhSrifUPKtu7qjbtrFo3Pz1SIg0f+BqJ5bENduibRr7C4AY/V00MOkd74MnoHkK0vKhPjoGhBcbXysPQtcd1CAk+1qac4darUmeeyVj42iuxUWj1f00kRsB2+I6zro/Ot2LGdVNkXI0uCPEh7MNHWQcrmXEyocALwzr2S0EZAX++epoi3yR+fRBWcZ3RUh4MIizDvOQnhZE3BVJxslQV7OSNvB3GSAiJYD9SwzoduGwwBzxVwIe0eOFKv/e87ca7yx6U2Oj6+u84662oTKaUzE7B1JX5QmP1yaoofPKBgfP+sujf5uEOI6DYTZpPcGCBpXO0zOg+kg/cQkwNIEkPIwEYpGobHhbPW6AoPVBTdoxu+aI57kZJ9z+drIeq9MhWYy8b+7HcQTNTsMdpwzpYzHb54v0Ejdya3BeG9y67fGxACd8bxzxni0D2SVAgIcGV2usqyERxxsZKljQH4OVsqZPOkL9eGs6XGosBlJseCV8isppA6lZrJQ3AtHWuM2ik01jptaxZfJ26cQKtHGywjFNEyi
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ghcr-pull-secret
      namespace: promptyard-dev
    type: kubernetes.io/dockerconfigjson
