apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ghcr-pull-secret
  namespace: promptyard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCSrnpqLQqUDizXm6bCduCt9J9byqMcNeanyB/+SIdishPq6OQZho2wPg6xfVFdTjYL7nd9mylJy4vQw6OCMKf6myKa4NOP+I1mp2EczG7EGc4OcF9lXHZJA0LSFBTm3uWXUt9UPNzE/hgnCpieeWEC/egt9ogR//ugVeWe9y/KjX2/p+R/iZw2B4h+dxocN2mb6VBvEiOiVlggjwO0bsfM+KJIDDBQpvSb43uHXi0HX9mpRu1je0iR1IU5MeVtF0bJGbkjvOxJizKiZvr0MVXbHcQzRAVzAoffJHMQMiHVKfIOlc7+97ZZpQ7Q4ZMPEjzciy63yeBhsRZ0NxK1xa+Xp3ylqYfNt25k8s15yZ92r7pekAOaCIaP+gh6lkAX7cgwW3i+5SZ/jwswX//28J/KeTcZ16ajMPfKIVR8QobWmHpfojJ/oDqW4JR+2UE+1CmZAg4Y/r+aTsNcbPLlfQirhXs1G6aFnPnNktY90uh2kMIjHwwVlOzaBh33o41qsUXaSdLvihi7xGZV2jav10M4thwpSeoTSAVlU305VhqK6p3sBZf2gqkrlPmrofHTIdgNrdJETlxkuQ4a7GhCzoXxT0lusXvkldqt3SzEAf0EC7JuZHkVp+q5df/VJTGCYGb4B50JuB3aTFySZ5z5EJvkAwhFeKKmpW7sV7lKfwS9MzjMqYmCPiemwNQdmiLzGxJAsoJUrDCfRsc7mRFc1ZQ8bHdIzxq4i4V9sQQ0ldFml2h0urr7vNaj3WE0skdbx+e4pVfUrJgawD7nLw1ukBYXSbsSHyBhHCkvlGCHo/NCaY0wLNQfQ4dzz2BVJyWVzNocGVee1TclAStm3bHPkGxjd5BgYv6S0+1wXrcGp10TTTbeNxH5GPFhQwJ2gxo4P1IIEEwbb8rncu8aGIPsPyTtot+abrLv8fbY9DT8JFKAI/2oGYffHiINnTWQ9fLgZ2dE3v795gb++wvLO/mdZhenTkZ39FExmkBciV/VEOtn9KN9U1JDZqlHMaAa0EskEbZs3BDZ+GaDVXXdRQvW6EMd2t1q7S6MuqA/6LrvAzmEZkmcLiGOV5BulULYxDzUCAH6XdPJlU1w3tnjK5e4ZUNtQw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ghcr-pull-secret
      namespace: promptyard-dev
    type: kubernetes.io/dockerconfigjson
