apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: ghcr-pull-secret
  namespace: promptyard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCfZxhZeMbIp+jK16hcz6rskFQ+iBrQJSPGLOC5vEvUzuP8qhkuauzRK3A6tMzWw/RbScsfEQb2CCvjMZGF+fe3JamPO4aIX2VEWz/UNCljlnGnX8vV/FL835IQE0R+KXMGqQCNYMmUoGiuOaVq38F/fBHJA5IhzNoH3KnN5kzGbRgZMm7Q6lbV4Yr7zZW5iWKg2TymAFehr+ubFqRDwrz3p/DBLGuqHAW0oDwv9evinJyozRjNxO5RilwGzZB3pgQx4g2O8x4b55crkYhjk9Aeu0wwqtPka85tIXRCo3CuXjUjSG8cS9bdUtTyIgVmO5hZE5Yfm6ofLQyO7rprZzAgGiLmaJtenLx5Ey/CoY1T0F1ehDfuDCPjz2tSh2AI2VhV125JsMsm4BON84ZHWgXiA5sNbR62cXlWMOwpw5pPWdDie8Jy3Ad5RItOcJ8oAx/HY5wZyjs2Toagphxxo4f03TuF8tpT/vF+XAzXAVw58NQ67Pp3w0LtQvkC8Ov5ZhuYUmglhyMvivnZ8LGQEneBSL6c42Xo79fLoM9R15h/7o4VjK9fQw5z/2IxI54Tkaz5rpiKuUkccZbqGKFzCQZWuKLvWTaYy/q/UoSJlTY71VRdZkYnOFYYt8Oz/mJ4pHJvd6ap7fsXsl86nBqT2Zio56MWASAweiwznS8h6DD+yBOYHLNId15XoSdVUCdaiHxX4dXC7C7DWgvIuqM3YNZE29JFXM2X7oF5C0guaH/exbg1pYXXVk4rWQLo5l7VtUEO9kwAm05Hb0JwwzepH9OccwBOiPBAJxF3T2bYLBGGUI47KY0RiJtrEswFJBPw8gvDbmQftH4wwEsePncyHwUBl3KmTziolXvn7N7m9338LwwZ52fBn/3n+r1IUMamvoDXwjpHCQV9ppAqx/rPS6GGHnK6dFVnsPL0mZ9e+xQHUejk9xA9UyGJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: ghcr-pull-secret
      namespace: promptyard-dev
    type: kubernetes.io/dockerconfigjson
