apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/server
  - sealed-secret.yaml
namespace: promptyard-dev
images:
  - name: ghcr.io/infosupport/promptyard
    newTag: 0024ef5e517a233113c2027978be5852abe6780f
configMapGenerator:
  - name: promptyard-server-config
    literals:
      - QUARKUS_OIDC_AUTH_SERVER_URL=<your-oidc-auth-server-url>
      - QUARKUS_OIDC_CLIENT_ID=<your-oidc-client-id>
      - QUARKUS_DATASOURCE_JDBC_URL=<your-jdbc-url>
      - QUARKUS_OPENSEARCH_HOSTS=<your-opensearch-hosts>
generatorOptions:
  disableNameSuffixHash: true

