apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: promptyard-server-secret
  namespace: promptyard-dev
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    QUARKUS_OIDC_CLIENT_SECRET: "AgBS/BV6fNxd2crS5HNhID9fqxfX67FZvYfpkr02rzipZ6tuzC2M5bMFiBc8Ln7L5+XTyxEF1N0zVu+gEvPhjAJvPVpLHFKTZqVg1j6qI0yzbbNEYpPt82LGLd11hfz95c4RVtqyCaP75f/1j7x6hWnPAeJqo8BOYnn9PdjwLQAt3vyawxqxHG+4Zj0iZOeh/HYuobUtDYW5oY0bZe85B9sclJX1jyMtxjMTyqayNUix9fKfdbbuXHZXTFaIkeKESrvPz5hq/jYOnY+kax80zVlYaf/BrBdiq+iLYhqOybHZeZFAOYTch19ErpsBMDiGagzFFQ3cQryW3zRCC5Rji/o2F5iqS/1O6Tf7QZYVDIWvJFMezNCaCq0p56Cfv8bGfHRweAAyrDfZZokfU9sQDasgQHM5SVfvPg+D3DQRBaPJcTNnzR46ClrRa6HnXTdwF3zTzq2jiwjx9kEYZ0w4CYuo5e3hLXHhDyVUoDy1m9EBtZLWVezie0hXhtTEpgjJyQGDIZGwl7EM56Bbxl9W+3goR4UdgWCaiumJxccG+MwB4hE7SymLkKaLSIV58Xpbp6RhKAm/Tt1PVDK4HXD4JOfMGxBc6CujtEEI0fB5kx4fo9UkpNbfN6lYNM/06s1lE+6Lcg71EoasNvBXPbNn1+jH61LFqN6e8KCW/OO1d7UUPh7UVdZlHurRYwmLWuKeuZVN+O6v"
    QUARKUS_HTTP_AUTH_SESSION_ENCRYPTION_KEY: "AgCRiqnGF+Pu7B7JFKfbbkRdI5GtfsPlDU/zvW6bY2bTLfKBHkWw92jEvmKV26H7z5bPrTHiLol7Z5sXwnlBb8GhbfGEYXACcLRgxgqGRwkXzKuepJ55/8TK7XBfMm0xVpP0wGVMPIeHduMKEPQLqRA5FAx9Rl7DAfCsXyUC0fa0WhZV3mmwWby4Uk0uvEdANPujMBaRfs61rFXVwefbRoGJlthG+5M5tsi+wK/N8faIbMXCHpNUeDiZl1v2UIWTaUQm7Q7nR+eEMPx5R6tOJ2GaTMsqXpvr+ueS75vlz2JbiEF5eCfpjvza9DTTYsRPViWtcaGApYoFH6T4KFY4k71v8MTiyW4AEDfy6AWxolfDS/5JJuDLMaSLZDPrCj31HJvFvLbIUOCdTYk/ga/eRh7duzQuYHmU3nYe4EMqcWWX1sUzh1qaeQ2AsmFpnOJiuPjL5UvunVa/gK3yEQKo0x3j1QeXxQSpJw0aPT6pWCx99MYlgbceaSSnjo85qEK1KbVJX0JRXiN3KDVeroLvhYPb/7eJfaYYk3KN4glsYAeoze3jivyuelzdHKnUysrTix8IzuhEYXUkZJZyHhComwZfqpE3K9FMLcJWaBES9Mh9ngYoaXNDLmBf0ucBZU7CBAMsNLupdSW06ybXPlSz6e/E3Mtf5HcEiU0avVLezzz/j8PvZxfh51p/HWoAP8AQsjUCERvfydKx8/F70EVEGJamBEc2BOHzXP3luKzNrc+8U6fTnLlGactOw2C0CwDg3NIocGkPq0q/EeCMD7SsRr51"
  template:
    metadata:
      name: promptyard-server-secret
      namespace: promptyard-dev
    type: Opaque
